#ifndef CONSTANTS
#define CONSTANTS

#define KEY_TO_CRYPT "666"

#define ADMIN_MENU "1. Add Student\n2. Get Student Details\n3. Add Faculty\n4. View Faculty Details\n5. Activate Student\n6. Block Student\n7. Modify Student Details\n8. Modify Faculty Details\nPress any other key to logout"
#define ADMIN_LOGOUT "Logging you out"

//add student
#define ADMIN_ADD_STUDENT_NAME "What is the student's name?"
#define ADMIN_ADD_STUDENT_AGE "What is the student's age?"
#define ADMIN_ADD_STUDENT_EMAIL "What is the student's email?"
#define ADMIN_ADD_STUDENT_ADDRESS "What is the student's address?"
#define ADMIN_ADD_STUDENT_AUTOGEN_LOGIN "The autogenerated login ID for the student is : "
#define ADMIN_ADD_STUDENT_AUTOGEN_PASSWORD "The autogenerated password for the student is : "

//add faculty
#define ADMIN_ADD_FACULTY_NAME "What is the faculty's name?"
#define ADMIN_ADD_FACULTY_DEPT "What is the faculty's department?"
#define ADMIN_ADD_FACULTY_DESIG "What is the faculty's designation?"
#define ADMIN_ADD_FACULTY_EMAIL "What is the faculty's email?"
#define ADMIN_ADD_FACULTY_AUTOGEN_LOGIN "The autogenerated login ID for the faculty is : "
#define ADMIN_ADD_FACULTY_AUTOGEN_PASSWORD "The autogenerated password for the faculty is : "


//admin mode updates
#define ADMIN_UPDATE_STUDENT_ID "Enter the ID of the student who's information you want to edit"
#define ADMIN_UPDATE_STUDENT_MENU "Which information would you like to modify?\n1. Name 2. Age 3. Email 4. Address \nPress any other key to cancel"
#define ADMIN_UPDATE_STUDENT_NAME "Enter updated name of student"
#define ADMIN_UPDATE_STUDENT_AGE "Enter updated age of student"
#define ADMIN_UPDATE_STUDENT_EMAIL "Enter updated email of student"
#define ADMIN_UPDATE_STUDENT_ADDRESS "Enter updated address of student"

#define ADMIN_UPDATE_FACULTY_ID "Enter the ID of the faculty who's information you want to edit"
#define ADMIN_UPDATE_FACULTY_MENU "Which information would you like to modify?\n1. Name 2. Department 3. Email 4. Designation \nPress any other key to cancel"
#define ADMIN_UPDATE_FACULTY_NAME "Enter updated name of faculty"
#define ADMIN_UPDATE_FACULTY_DEPT "Enter updated department of faculty"
#define ADMIN_UPDATE_FACULTY_EMAIL "Enter updated email of faculty"
#define ADMIN_UPDATE_FACULTY_DESIG "Enter updated designation of faculty"


#define ERRON_INPUT_FOR_NUMBER "It seems you have passed a sequence of alphabets when a number was expected or you have entered an invalid number!\nYou'll now be redirected to the main menu!^"
#define AUTOGEN_PASSWORD "academia" 



#define STUDENT_FILE "./functionalities/records/student.txt"
#define FACULTY_FILE "./functionalities/records/faculty.txt"
// #define TRANSACTION_FILE "./records/transactions.txt"


#endif